// src/views/login/index.tsx
import { Button } from "antd";
import { useNavigate } from "react-router-dom";
import { setLocal } from "../../utils/auth";

const Index = () => {
  const navigate = useNavigate();

  /**
   * 登录
   */
  const handleLogin = async () => {
    navigate("/dashboard", { replace: true });
    setLocal("token", "zxiaosi")
  };

  return (
    <div style={{
      position: "absolute",
      top: "50%",
      left: "50%",
      transform: "translate(-50%, -50%)",
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
    }}>
      <h1>登录页</h1>
      <Button type="primary" onClick={handleLogin}>点击登录</Button>
    </div >
  );
};

export default Index;

// src/views/Login.vue
<script setup lang="ts">
import { useRouter } from "vue-router";
import { setLocal } from "@/utils/auth";

const router = useRouter();

/** 提交表单 */
const handleSubmit = () => {
  setLocal("token", "zxiaosi");
  router.push("/");
};
</script>

<template>
  <div class="page">
    <h1>登录页</h1>
    <el-button type="primary" @click="handleSubmit()">点我登录</el-button>
  </div>
</template>

<style scoped lang="less">
.page {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  display: flex;
  align-items: center;
  flex-direction: column;
}
</style>
